services:
  # Web service
  - type: web
    name: genesis
    env: docker
    region: oregon  # Choose the region closest to your users
    plan: free  # Adjust as needed: free, starter, etc.
    branch: main  # Deploy from the main branch
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: GOOGLE_API_KEY
        sync: false  # This will be set manually in Render dashboard