services:
  # Web service (API)
  - type: web
    name: genesis-api
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r app/requirements.txt && pip install aiofiles
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: API_HOST
        value: 0.0.0.0
      - key: API_PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false  # This will be set manually in Render dashboard
      - key: GOOGLE_API_KEY
        sync: false  # This will be set manually in Render dashboard

  # Static site (Frontend)
  - type: web
    name: genesis-frontend
    env: static
    region: oregon
    plan: free
    branch: main
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /api/*
        destination: https://project-genesis.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html